repo_name: "Video-streaming-app"
repo_url: "https://github.com/goth7mog/{{ repo_name }}"
git_clone_dest: "/home/{{ ansible_user }}/{{ repo_name }}"
synchronize_src: "/Users/alexander/Code/Development/Larissa_docs/Development/VideoApp/"
synchronize_dest: "{{ ansible_user }}@{{ ansible_host }}:{{ git_clone_dest }}"

