---

# - name: Initial setup as root
#   hosts: droplet1-root
#   vars_files:
#     - vault.yaml
#   roles:
#     - create-main-user


- name: Full site setup
  hosts: droplet1-main
  become: yes
  vars_files:
    - vault.yaml
  roles:
    - initial-setup
    - ufw
    - role: git-clone
      become: false
    - nfs-server
    - docker-setup
    - k3s
